sudo: required
dist: trusty
# dist: xenial

language: cpp
compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y qtbase5-dev-tools qtdeclarative5-dev qt5-default
  - sudo apt-get install -y libqt5quicktest5 qtlocation5-dev qtpositioning5-dev #libqt5quickcontrols2-5

script:
  - qmake . -recursive
  - make
  - make check

after_success:
  - echo "success"
 
after_failure:
- echo "failure"
