sudo: required
dist: trusty
# dist: xenial - no support yet by travis :(

language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # works on Trusty
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - llvm-toolchain-trusty
#          packages:
#            - clang-4.0
#      env:
#        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -y  qt59base qt59declarative qt59location qt59quickcontrols qt59quickcontrols2 qt59sensors qt59svg qt59tools
  - source /opt/qt59/bin/qt59-env.sh
  - export QTHOME=/opt/qt59
  - export export QML2_IMPORT_PATH=src

script:
  - qmake . -recursive
  - make
  - make check
