sudo: required
dist: trusty
# dist: xenial

language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -y qt59-meta-full
#  - sudo apt-get install -y  qt59base qt59declarative qt59location qt59quickcontrols qt59quickcontrols2 qt59sensors qt59svg qt59tools
#  - sudo apt-get install -y qtbase5-dev-tools qtdeclarative5-dev qt5-default qttools5-dev-tools
#  - sudo apt-get install -y libqt5svg5-dev libqt5sensors5-dev qtlocation5-dev qtpositioning5-dev
#  - sudo apt-get install -y libqt5quicktest5 #libqt5quickcontrols2-5

install:
  - source /opt/qt59/bin/qt59-env.sh ; export QTHOME=/opt/qt59

script:
  - qmake . -recursive
  - make
#  - make check

after_success:
  - echo "success"
 
after_failure:
- echo "failure"
