name: baugeschichte
version: 2.0.2.2
summary: See images and the history of builings in a city
description: See images and the history of builings in a city downloaded from www.housetrails.org
confinement: strict
grade: stable

apps:
    baugeschichte:
        command: qt5-launch opt/Baugeschichte/bin/Baugeschichte
        plugs: [x11, unity7, home, opengl, network, network-bind]

parts:
    baugeschichte:
        plugin: qmake
        qt-version: qt5
        source: src
#        source: https://github.com/gschwann/Baugeschichte.git
#        source-type: git
#        source-branch: master
        build-packages:
            - build-essential
            - qttools5-dev-tools
            - qtbase5-dev
            - qtdeclarative5-dev
        stage-packages:
            - libqt5concurrent5
            - libqt5core5a
            - libqt5declarative5
            - libqt5gui5
            - libqt5network5
            - libqt5qml5
            - libqt5quick5
            - libqt5svg5
            - libqt5x11extras5
            - libqt5xml5
            - qml-module-qtquick2
            - qml-module-qtquick-layouts
            - qml-module-qtquick-controls
            - qml-module-qtquick-xmllistmodel
        after: [qt5conf] # for qt5conf see https://github.com/dplanella/qt5conf

